### ISSUE TITLE
Spot cleaning 

### ISSUE THREAD

**Issue by webjib** [pooyashahidi/xiaomi_vacuum#1]
Hello. Very good job to refactor all components for the Dreame D9!
I've started to alter the code as well, but not as much as you did ;-)

I've tried to implement a "Spot cleaning" function, but without any luck. Did you manage to do so?
It seems that the payload with value "20" has no effect...

```@command()
     def clean_spot(self) -> None:
         """Spot Cleaning."""
         payload = [{"piid": 1, "value": 20}]
         return self.call_action(4, 1, payload)
```

**Comment by pooyashahidi** [comment]
I was looking into it today but was distracted by the remote control, service because spot cleaning need some sort of remote control to first get the bot there :D  The remote control seems to do what it wants no matter the parameters ( better said, I'm probably mistaking what the parameters mean).

**Comment by webjib** [comment]
Actually, I would like to reproduce the behaviour of the physical button 'spot cleaning'. Usually, I take the robot myself to put it on the dirty spot. That said, it's easy for me to press the physical button on the robot, but I would be cool to have it on the Vacuum Card as well.

I thought that starting the robot with the "value" set to 20 would do the trick but it's not working :( That's weird, because fast map is working (when you set value to 21).

Last, maybe it's not supposed to work. After all, the Xiaomi Home app does not have a "spot cleaning" button, so maybe the robot is not supposed to treat this command.

**Comment by pooyashahidi** [comment]
My hunch is that it needs additional info "piid":10 like room cleaning and zone cleaning both do. probably to specify how large the spot should be. if only we had some sort of documentation...

**Comment by webjib** [comment]
Oh you're probably right! I'll run some tests in that direction.

**Comment by pooyashahidi** [comment]
Please let me know if you had a breakthrough.  

In the meantime I figured out how the values to remote control work. I will correct the service definition for it.
it's pretty odd, like the robot moves `one time unit` let's say 2 seconds every time I send a command.   
- The `spdv` property is the speed it moves in that window of time. Maximum +100 (forward), Minimum -300 backwards. 
- The `spdw` is the angle measured in binary degrees so 64 means 90° CCW and -64 means 90° CW. Maximum 128, Minimum -128

These two can be combined to move in sort of an arc.

**Comment by xury77** [comment]
Hi. You mean spot cleaning as  just a small point, or as a rectangle clean zone? How to use a clean zone? I managed to send  the vacuum to clean zone on https://github.com/microfrost1/xiaomi_vacuum version, but still can't do it on your fork.

**Comment by pooyashahidi** [comment]
> Hi. You mean spot cleaning as just a small point, or as a rectangle clean zone? How to use a clean zone? I managed to send the vacuum to clean zone on https://github.com/microfrost1/xiaomi_vacuum version, but still can't do it on your fork.

Hi there, yes the spot cleaning as in clean the 1.5mx1.5m "spot" that the robot is at. Just like pressing the button on the thing itself. Unfortunately I could not find any documentations on what extra payloads it requires to perform spot cleaning.

About the zone cleaning; I added examples in all of the service definitions.  You can press the `Fill example data` button in home assistant's `developer tools` and check how the data should look like. 
![image](https://user-images.githubusercontent.com/5418119/126304989-502e3855-881e-489f-8be9-887950c2bcfe.png)


Maybe there is a difference between the data that this version expects and the one by microfrost1. These two versions could have lots of difference now as I changed a lot of stuff and tried my best to make it easier to use and develop further ( if needed )
