### ISSUE TITLE
Dream l10 don’t work rooms clean

### ISSUE THREAD

**Issue by beliy1985** [pooyashahidi/xiaomi_vacuum#10]
Hi, i ask for help, why it does not work:
rooms: [[ 'A', 2, 4, 3],[ 'B', 1, 2, 3]]

Repeats work,clean_mode,mop_mode does not work. Always values from the last group it is also applied to all rooms

**Comment by pooyashahidi** [comment]
Hi, sorry for the delay I was on vacation.  Unfortunately I do not own a L10 to test :( so I probably wont be able to fix this. But there is a [similar thing](https://github.com/pooyashahidi/xiaomi_vacuum/blob/6fa50ec882bf76a06402ec576e17bcf30d7fb889/custom_components/xiaomi_vacuum/miio/dreamevacuum.py#L315) with zone cleaning that I could not figure out.
I have a feeling that the fact that it works is also probably not planed as it is not used in the app. Maybe it will stop working in future D9 firmwares.

**Comment by beliy1985** [comment]
I'm rooting robot,  please tell me how you control the valetudo segments? I have lost all the timers and the card and now I don't understand how to manage the number of repetitions in the segment again

**Comment by pooyashahidi** [comment]
if you have valetudo you won't be able to use the mi home app to create a new schedule (until valetudo adds the ability to create schedules). In that case room characters won't show up in this integration. you should still be able to call room cleaning like before, 'A' will be the first segment created, 'B' the next one and so on.

**Comment by beliy1985** [comment]
It works, thank you, I thought I had lost this function
