### ISSUE TITLE
dreame.vacuum.p2041o (Xiaomi Robot Vacuum Mop 2 PRO+) error

### ISSUE THREAD

**Issue by FrancYescO** [pooyashahidi/xiaomi_vacuum#11]
I've started using the custom component where you started the fork (microfrost1/xiaomi_vacuum) and was working, i've just tried yours to get the various fixes but it fails to setup, are you interested to get it fixed for this device?

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 653, in update
    state = self._vacuum.status()
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 203, in status
    {
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 204, in <dictcomp>
    prop["did"]: prop["value"] if prop["code"] == 0 else None
KeyError: 'value'
```

**Comment by pooyashahidi** [comment]
@FrancYescO  if I'm not mistaken that error suggests a property from the mapping is missing. 
Could you please check to see which one is it?

**Comment by FrancYescO** [comment]
As you can see from the PR is "did"

**Comment by pooyashahidi** [comment]
I can see the error. The reason for the value not existing is that you are using the [mapping made for Dreame D9](https://github.com/pooyashahidi/xiaomi_vacuum/blob/c332b44d90ddc9590eff140312598dab9e98a793/custom_components/xiaomi_vacuum/miio/dreame_const.py#L3)  with another device which does not have the same properties.

Can you create the correct mapping for your device? If not I will add the check as a workarround for using the wrong mapping.

**Comment by FrancYescO** [comment]
afaics, the mapping is the same as all states are congruent while using my device

**Comment by pooyashahidi** [comment]
Okay thanks for the PR I merged it. should I add your device to the list of supported devices? in other words is there anything else broken?

**Comment by FrancYescO** [comment]
Actually i didn't find anything broken, properties are shown okay i still need to do some testing for room cleaning 
![image](https://user-images.githubusercontent.com/4574593/139719035-a89afe3f-e0b8-4bf7-87a3-18eacc02e2b2.png)
