### ISSUE TITLE
Entity vacuum.dreame (<class 'custom_components.xiaomi_vacuum.vacuum.MiroboVacuum'>) implements device_state_attributes. Please report it to the custom component author

### ISSUE THREAD

**Issue by pergolafabio** [pooyashahidi/xiaomi_vacuum#15]
Hi, since updating to 2021.12.x i receive error below, probably a breaking change?

`[homeassistant.helpers.entity] Entity vacuum.dreame (<class 'custom_components.xiaomi_vacuum.vacuum.MiroboVacuum'>) implements device_state_attributes. Please report it to the custom component author`

**Comment by Timuridze1** [comment]
I confirm the mistake

**Comment by pooyashahidi** [comment]
> Hi, since updating to 2021.12.x i receive error below, probably a breaking change?
> 
> `[homeassistant.helpers.entity] Entity vacuum.dreame (<class 'custom_components.xiaomi_vacuum.vacuum.MiroboVacuum'>) implements device_state_attributes. Please report it to the custom component author`

Thank you for reporting this. Since my vacuum died I do not use this project (untill i can get a new one).
Please check against master branch if the problem is solved I make a new release.

**Comment by pergolafabio** [comment]
Ok, will check tomorrow! Keep you posted...

Thnx

**Comment by pergolafabio** [comment]
its fixed! just tested, dont see the error anymore
