### ISSUE TITLE
Get zone coordinates

### ISSUE THREAD

**Issue by XaviosTheBoss** [pooyashahidi/xiaomi_vacuum#16]
Hello,

First of all, thank you for your work. I have a Dreame L10 Pro vacuum and your integration is great. I am interested in the xiaomi_vacuum.vacuum_set_restricted_zone or xiaomi_vacuum.vacuum_clean_zone feature which use coordinates. However, I don't know how to get the coordinates that would be already defined in the app. One solution would be to use the Xiaomi Cloud Map Extractor integration, but Dreame is not supported (yet).

Do you have a solution to get (defined) zone coordinates ? 

Thank you.

**Comment by pooyashahidi** [comment]
Hi
There is a modified version of Mihome for android usually used to extract device tokens and stuff. That app has logs written in your internal storage. One way would be to execute a command in that app and check its logs. It outputs exactly the coordinates that you want.

There are probably other ways to do it. My bot died a while ago so I don't really have a way to test it for you.

Looking at the code for `set_restricted_zone` it uses set `action_set_map` which is `{"siid": 6, "aiid": 2}`.
There is also a `action_req_map`  `{"siid": 6, "aiid": 1}` that if I remember correctly I could not get any usefull info out of. If you feel adventurous you can try python-miio and play with it.

There is also some movement in the map extractor repo that you mentioned ( too late for me lol )
