### ISSUE TITLE
Config error - No module named 'click'

### ISSUE THREAD

**Issue by jaegerschnitzel** [pooyashahidi/xiaomi_vacuum#18]
I'm using the add-on Check Home Assistant configuration for testing my configuration before updating the core.
Unfortunately the add-on points out the following error:
`Platform error vacuum.xiaomi_vacuum - No module named 'click'`
Updating works fine and I don't see this error in my HA log.
Can you please have a look and fix this?

**Comment by pooyashahidi** [comment]
What add on? You really did not provide any info on what exactly is the problem. Just that some addon you use for something else has a problem with Click.
Click is used by Miio for their command line stuff not really needed here IIANM.
I made a branch without it called "no_click" you can try that one. I currently do not use this library until I get another vacuum, so you have to test for yourself.

**Comment by jaegerschnitzel** [comment]
The add-on [Check Home Assistant configuration](https://github.com/home-assistant/addons/tree/master/check_config) checks whether your configuration files are valid against the new version of Home Assistant before you actually update your Home Assistant installation. This add-on will help you avoid errors due to breaking changes, resulting in a smooth update.

Here is the full output of the add-on:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:05:50] INFO: Don't worry, this temporary installation is not overwriting your current one.
[22:05:50] INFO: Installing Home Assistant: stable...
[22:05:50] INFO: Please be patient, this might take a few minutes...
[22:06:18] INFO: Installed Home Assistant 2022.2.2
[22:06:18] INFO: Making a copy of your configuration for checking...
[22:06:18] INFO: Checking your configuration against this version...
[22:07:13] ERROR: The configuration check did not pass!
[22:07:13] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Platform error vacuum.xiaomi_vacuum - No module named 'click'

Successful config (partial)
[22:07:13] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

Thanks for your fast response and the new version. I tested it but I get the following error:
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/xiaomi_vacuum/miio/device.py:124
Integration: Xiaomi Vacuum (documentation)
First occurred: 22:15:56 (1 occurrences)
Last logged: 22:15:56

Unexpected exception importing platform custom_components.xiaomi_vacuum.vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 583, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 7, in <module>
    from .const import *
  File "/config/custom_components/xiaomi_vacuum/const.py", line 2, in <module>
    from .miio.dreame_const import (
  File "/config/custom_components/xiaomi_vacuum/miio/__init__.py", line 1, in <module>
    from .device import Device
  File "/config/custom_components/xiaomi_vacuum/miio/device.py", line 124, in <module>
    class Device(metaclass=DeviceGroupMeta):
NameError: name 'DeviceGroupMeta' is not defined
`

**Comment by pooyashahidi** [comment]
That is an interesting Idea. thanks for sharing the addon.

Whoops, I forgot to delete some of the references. Do you mind trying the new beta release? v1.3b2_No_Click

**Comment by jaegerschnitzel** [comment]
You're welcome.

I tested the new version and the first error disappeared. But now this error occurs:
> [22:09:37] ERROR: The configuration check did not pass!
> [22:09:37] ERROR: See the output below for more details.
> Testing configuration at /tmp/config
> Failed config
>   General Errors: 
>     - Platform error vacuum.xiaomi_vacuum - No module named 'construct'
> 
> Successful config (partial)

Since the real update does not show any errors I'm not sure if this is worth fixing. Perhaps you can test the add-on and find out why these kind of errors appears.

**Comment by pooyashahidi** [comment]
Hmm :/ these are all python libraries used in python-miio. it is really odd that the addon is complaining about them.
Unfortunately I do not have a physical vacuum device right now to test it as my D9 died months ago. I just try to keep this thing running for people who currently use it, at least until I get another device and start working on it again.
Click was not really needed in this integration, as it is used for python-miio's command line stuff but I fear construct is.
I'm not a python expert but I beleive the config addon should not throw errors about these libraries.

**Comment by jaegerschnitzel** [comment]
Thanks for your effort.

I saw a few other users which have also problems with the [Check Home Assistant configuration](https://github.com/home-assistant/addons/tree/master/check_config) add-on. [For example](https://community.home-assistant.io/t/update-notifications-core-hacs-supervisor-and-addons/182295/1):
> It also still includes the piece to run the core_check_config addon so the notification can include the status of that output although truth be told I haven’t been able to trust that addon for a while. I keep getting false error messages about bad python dependencies which I then just have to ignore since they don’t make any sense. They’re always about packages that if they were actually missing HA’s CI never would’ve passed in the first place. For now I’m leaving it in but jury is still out on the usefulness of that check these days.

So I guess everything is fine and we can ignore these errors.
