### ISSUE TITLE
Add audio level service

### ISSUE THREAD

**Issue by webjib** [pooyashahidi/xiaomi_vacuum#2]
In my own custom implementation, I've created a service to set the audio level of my Dreame D9. Then I've added an input_number in Home Assistant, that take "audio_volume" as an input, and uses the new service when the slider changes.

Could be nice to add this service in your implementation too :-)

<img width="1094" alt="Capture d'écran 2021-06-28 à 13 43 10" src="https://user-images.githubusercontent.com/33569886/123631710-582b1d00-d817-11eb-9251-6ddd7ef630ee.png">

**Comment by pooyashahidi** [comment]
Thanks for the tip :) will do.

**Comment by pooyashahidi** [comment]
Done in 86ea06e87cd3dc66fd42562273ed834a30ebe617.
Also used the volume test to hear the changes every time :)

**Comment by webjib** [comment]
Perfect!
