### ISSUE TITLE
How I get the controls posted in the documentation ? 

### ISSUE THREAD

**Issue by DirkStorck** [pooyashahidi/xiaomi_vacuum#20]
Hi, 

is there somehow an example how I can add these cards? 

![image](https://user-images.githubusercontent.com/2306190/164912193-c01fc4d1-a5e8-464e-bad6-3d8d2fe0e38c.png)

Thank you!

**Comment by pooyashahidi** [comment]
Hi I posted the code in issue #8

**Comment by DirkStorck** [comment]
Hi,

thanks for sharing your code. 
Didn't know where I have to put the code from 
https://gist.github.com/pooyashahidi/b3a7e1859d9f6d5751047b391fce09ec
and since I don't have Valetudo flashed on my vaccum I can't use the map I have decided to use some piece from your code which worked quit well.

![grafik](https://user-images.githubusercontent.com/2306190/165039495-4c4a75fe-3c54-42ac-ab78-646fae59f2aa.png)

The only problem that I have is that for example the for the "Main Brush time left value" getting displayed I get the code displayed instead.
I tried to recreate the problem with an entity card and getting the same problem 
![grafik](https://user-images.githubusercontent.com/2306190/165039770-e247fe20-5205-4289-8d91-61e2f782e16c.png)

Could you please tell me what I do wrong? 

`
type: entity
entity: vacuum.dreamed9
attribute: main_brush_time_left
name: |
  [[[
    return "Main Brush  -  " + states['vacuum.dreamed9'].attributes['main_brush_time_left']+"h";
  ]]]


`

Thanks so much!

**Comment by pooyashahidi** [comment]
You have the same problem as the issue I linked before. I mentioned this in that issue too.
I don't really remember what I did to make the js portions [[[...]]] work in home assistant. It's probably something I installed back then when I configured my home assistant and do not remember anymore. but there is an integration that helps you create templates using variables. It is called "config-template-card" you can use that one to achieve something similar.

**Comment by DirkStorck** [comment]
Thank you, will try that.

**Comment by DirkStorck** [comment]
Hi,

have got it working now 

![grafik](https://user-images.githubusercontent.com/2306190/165271464-454cecde-8b72-4694-9625-e4ec2ca3169a.png)

`
type: entities
title: Status & Information
entities:
  - entity: vacuum.dreamed9
    name: Dreame D9
    icon: mdi:robot-vacuum
    tap_action: null
    action: more-info
  - type: custom:template-entity-row
    name: Water Container
    state: >-
      {% if  is_state_attr('vacuum.dreamed9', 'waterbox','removed')%} Removed {%
      else %} Present {% endif %}
    icon: mdi:watering-can
    entity: vacuum.dreamed9
    tap_action: none
  - type: conditional
    conditions:
      - entity: binary_sensor.d9_active
        state: 'on'
    tap_action: none
    row:
      entity: vacuum.dreamed9
      type: attribute
      name: Cleaned Area
      attribute: cleaning_area
      suffix: m²
  - type: conditional
    conditions:
      - entity: binary_sensor.d9_active
        state: 'on'
    tap_action: none
    row:
      icon: mdi:timer-outline
      entity: vacuum.dreamed9
      type: attribute
      name: Time
      attribute: cleaning_time
      suffix: m
  - entity: vacuum.dreamed9
    icon: mdi:ruler-square
    type: attribute
    name: Total Cleaned Area
    attribute: total_cleaning_area
    suffix: m²
    tap_action: none
  - type: custom:config-template-card
    variables:
      - states['vacuum.dreamed9']
    entities:
      - ${vars[0].entity_id}
    card:
      type: entities
      entities:
        - type: custom:bar-card
          entity: vacuum.dreamed9
          attribute: filter_life_percent
          icon: mdi:air-filter
          unit_of_measurement: ' %'
          width: 55%
          height: 2em
          decimal: 0
          positions:
            icon: outside
            indicator: 'off'
            name: outside
          severity:
            - color: Red
              from: 0
              to: 25
            - color: Orange
              from: 26
              to: 50
            - color: Green
              from: 51
              to: 100
          name: ${ "Filter  -  " +  vars[0].attributes['filter_time_left']+" h"}
        - type: custom:bar-card
          entity: vacuum.dreamed9
          attribute: main_brush_life_percent
          icon: mdi:car-defrost-front
          unit_of_measurement: ' %'
          width: 55%
          height: 2em
          decimal: 0
          positions:
            icon: outside
            indicator: 'off'
            name: outside
          severity:
            - color: Red
              from: 0
              to: 25
            - color: Orange
              from: 26
              to: 50
            - color: Green
              from: 51
              to: 100
          name: >-
            ${ "Main Brush  -  " +  vars[0].attributes['main_brush_time_left']+"
            h"}
        - type: custom:bar-card
          entity: vacuum.dreamed9
          attribute: side_brush_life_percent
          icon: mdi:fan
          unit_of_measurement: ' %'
          width: 55%
          height: 2em
          decimal: 0
          positions:
            icon: outside
            indicator: 'off'
            name: outside
          severity:
            - color: Red
              from: 0
              to: 25
            - color: Orange
              from: 26
              to: 50
            - color: Green
              from: 51
              to: 100
          name: >-
            ${ "Main Brush  -  " +  vars[0].attributes['side_brush_time_left']+"
            h"}
`
