### ISSUE TITLE
Voice Packs

### ISSUE THREAD

**Issue by frauhottelmann** [pooyashahidi/xiaomi_vacuum#4]
Hey,
Thanks a lot for this integration. I looked around for voice packs.
Here is the official list: https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2009/voices/soundpackage.json
I installed the German version with no problems!

I don't know if you want to add the link to the readme or not :shrug:

**Comment by pooyashahidi** [comment]
Thanks, I added them to the readme (9cb384b1eec265d82c55886d5a81693f3d8809e0).
The idea was to make installing custom packages easier, as the official ones are already available in the app. But having the links there wont hurt. Maybe someone uses other languages as the basis for their custom packs.
