### ISSUE TITLE
Seems working with MOVA L600 Robot Vacuum and Mop Cleaner dreame.vacuum.p2157

### ISSUE THREAD

**Issue by cokefd** [pooyashahidi/xiaomi_vacuum#5]
Hello,

So far seems like the sensors and the commands work with:
 MOVA L600 Robot Vacuum and Mop Cleaner
 dreame.vacuum.p2157
Just in case someone is wondering about how to control the Mova through HA.

**Comment by pooyashahidi** [comment]
thank you for reporting. Is there anything that is not working?

**Comment by cokefd** [comment]
Hello,

Still trying to figure out how the rooms and maps work, so, not entirely sure if they are broken.
So far, pressing "play" sends the vacuum to clean, and I am able to see all this statuses:
![image](https://user-images.githubusercontent.com/66829878/126890669-a4a89d3e-60b8-4874-a382-8bbe1b982966.png)

Thank you so much

**Comment by cokefd** [comment]
got a single map, but zone cleaning works as described. So far didn't find anything that doesn't work.

Thank you so much for your work. You might want to mention that this vacuum works with your code

**Comment by pooyashahidi** [comment]
yeah I tried my best to describe how to use room cleaning in the readme if you think any part can be improved feel free to let me know. the card in the screenshot is my own modified version not the original one but it is not public ( the code is too embarrassing to publish :D )
thanks for testing it I will add your model to the readme
