### ISSUE TITLE
 vacuum_set_multi_map not showing up as a service

### ISSUE THREAD

**Issue by Flipsoo** [pooyashahidi/xiaomi_vacuum#7]
Hey there,

again thanks for your fork and for your kind words. I have a little issue finding the service vacuum_set_multi_map - i assume its because D9 isnt supporting this feature but wanted to ask officially because im in hope that this is still somewhere possible because this would be a game changer for me

greetings

**Comment by pooyashahidi** [comment]
It was added after the first release. I will make a new release. I thought maybe that is not enough to justify a new release lol. The D9 should support it though.

**Comment by Flipsoo** [comment]
have seen it in HACS! thanks a lot for merging this in so fast will try it if im home again

**Comment by Flipsoo** [comment]
works like charme, service is visible and toggles the feature as expected - thanks again

**Comment by Flipsoo** [comment]
works like charme, service is visible and toggles the feature as expected - thanks again
