### ISSUE TITLE
Get Map ID

### ISSUE THREAD

**Issue by Flipsoo** [pooyashahidi/xiaomi_vacuum#9]
Hey, 
after successfully activating the Multi-map feature with the running service im struggling to get the map IDs from the created maps to select between them. Is it possible to get those informations somewhere? I saw the services select_map and rename_map but I don't get where to get those ids from

greetings and sorry if I missed this in the readme somewhere

**Comment by pooyashahidi** [comment]
Hi, well the problem is I don't know how to get the map ids - or segment ids for that matter - with miio. Hence the "schedule workaround" was used (as mentioned in the readme) but now that I have a rooted vacuum I cannot use Valetudo to create a schedule. If you only want to get the map ids from a rooted device you can find them here `/data/map` there is a folder for each map there. Name of that folder is your map id. I didn't have multiple maps back when my device was not rooted. If I can find a way to restore cloud functionality (for testing) I will probably try to find a way. But I cannot invest much time right now in this because of real life problems :( sorry

**Comment by Flipsoo** [comment]
hey no worries, this was the missing part - with taking this folders as id I can switch through the maps with the provided service from xiaomi_vacuum.vacuum_select_map. Good wishes for getting through hard times...

**Comment by pooyashahidi** [comment]
@Flipsoo  I don't think it is possible to achieve that by miio alone :-?
That said I personally don't think that it's a huge problem considering it can be done via the app using the schedule workaround for non rooted devices and by manually reading the values for rooted devices.

**Comment by Flipsoo** [comment]
Heey thanks for exploring this further and sadly it doesnt work. Ive looked into /data/map and the folders there always fluctuate. There are also some related things in: /data/DivideMap /data/DivideDebug /data/ri/ri.json /data/ri/backupInfo.json - but changing values there always resets, and copying the folders in map doesnt get them get loaded via the service . But as long as the robot stores a map its possible to have 3 different maps simultaneously and can change between them via the service💪🏽🤗 no real success but its a step closer:))

**Comment by uwej711** [comment]
Hi, I just came across this topic and would like to ask if you have any success with the multiple maps on your dreame vacuum. I have a rooted Z10 Pro with Valetudo and used miiocli to enable the multiple map feature. Carried robot and docking to the other floor and did a mapping pass. Now the robot has two maps in /data/map and information about the current map in /data/ri/ri.json. But it looks like I'm not able to change the current map (using miiocli with the parameters implemented here, maybe I did something wrong). Only when I change the ri.json file content and reboot the robot the map is changed. So my question is, does changing the map work in your setup? Are you still using xiaomi cloud?

**Comment by uwej711** [comment]
I just found my mistake ... I had to escape the value parameter for the action properly, then map switching works!

Reference for myself:

miiocli device --token <token> --ip <ip> raw_command action '{"did":<id>, "siid":6, "aiid":2, "in":[{"piid":4, "value": "{\"sm\": {}, \"mapid\":<mapid>}"}]}'
